### ISSUE TITLE
Searching a Randomized List and a Set List yields two different results

### ISSUE THREAD

**Issue by curtonius** [Zodsmar/SeedSearcherStandaloneTool#101]
I did a search with:
**Randomized Seeds: True**
Search Radius: 300
Incrementer: 10
Biome Precision: 16
Biome Set Ocean: Exclude
Swamp Hut: Include
Pillager Outpost: Exclude
Monument: Exclude

And saved the list of seeds. I then used that SAME search criteria just instead of **Randomized Seeds: True** I used **Set Seeds** and used the file I saved with the aforementioned list of seeds.

When I ran it again, with the SAME search, no seeds got outputted.

**Comment by Zodsmar** [comment]
As soon as you use structures you need to drop the Biome Precision. Having the biome precision so height will prioritize structures and therefore the seeds are the same. I can look to change the randomized seed section to automatically drop that value so the seeds are more random
