### ISSUE TITLE
doesn't run

### ISSUE THREAD

**Issue by omelette-du-fromage69** [Zodsmar/SeedSearcherStandaloneTool#104]
I downloaded the exe, and it doesn't run, am i doing something wrong?

**Comment by HotChocolateGG** [comment]
I'm having the same issue with both exe and jar for the 1.17 update.

**Comment by KnowOneWasTaken** [comment]
Same, both .exe and .jar for 1.17 doesn't run

**Comment by Zodsmar** [comment]
Yeah I realized this. No idea why. On my own system it works. But any other seems to break. I'm looking into it hopefully will have a fix soon

**Comment by omelette-du-fromage69** [comment]
the fix will be in the releases?

**Comment by Zodsmar** [comment]
> the fix will be in the releases?

Once it gets fixed yes

**Comment by RedTeaDev** [comment]
it works for me with
`java -jar  --illegal-access=permit .\sassa-v0.6.2.jar`

**Comment by majiajin2043** [comment]
![屏幕截图 2021-06-20 180754](https://user-images.githubusercontent.com/73528988/122670029-78912100-d1f2-11eb-9716-09426d55adbd.png)
me too 
Nothing happened after opening

**Comment by ThePlayingGoblin** [comment]
I'm having the same issue too. Neither the exe nor the jar will run. 0.6.1 though works just fine.

**Comment by Egamer25** [comment]
Still not fixed? Hope we can get a working version soon.  IN the meantime the old one seems to work... Just can't wait to see the new one.  Thank you for all the hard work.

**Comment by xanderk1** [comment]
to fix: Download Java 16, I use https://adoptopenjdk.net/ (Hotspot). Then open powershell (shift + right click in the same folder as .jar / .exe) then type "java -jar --illegal-access=permit .\sassa-v0.6.2.jar" To launch the program!

**Comment by Zodsmar** [comment]
Uploaded v0.6.3 should fix the issues.
