### ISSUE TITLE
Doesnt work when version is set to 1.13.2

### ISSUE THREAD

**Issue by bobbythejobby123** [Zodsmar/SeedSearcherStandaloneTool#11]
Works fine for 1.14 and above but when I set the version to 1.13.2 as I want to generate an XBOX 360 seed, even if I set it to only find one biome the rejected seed count and total rejected seed count just increase rapidly and no seed is ever found. I let the count reach about just over 1 000 000 before I had to just stop it manually.

**Comment by Zodsmar** [comment]
This isn't an issue with this tool. Amidst itself never got working in 1.13.2 and it had a lot of underlying issues. So if amidst ever updates and somehow finds a way to support 1.13.X then this tool will support it too. As for XBOX seeds this tool is built for Java seeds only at the moment. Sorry

**Comment by bobbythejobby123** [comment]
Ah I see ok thanks XBOX seeds are the same as Java seeds except for the mushroom islands. everything matches up in game except those darned mooshroom islands lol

**Comment by Zodsmar** [comment]
Didn't know that. Good to know thanks. Ill keep that in mind
