### ISSUE TITLE
GUI Issue

### ISSUE THREAD

**Issue by PeacePlays** [Zodsmar/SeedSearcherStandaloneTool#12]
As you can see in the image there are controls that are not visible under biomes leaving them not selectable for inclusion etc. 

While there were similar issues in the older versions all of the biomes could be selected. Running Java 8 221 / Mac OS 10.14.6

<img width="884" alt="Screen Shot 2019-09-07 at 11 43 56 AM" src="https://user-images.githubusercontent.com/49123331/64477746-dd39d380-d164-11e9-9e2a-690a66087897.png">

**Comment by Zodsmar** [comment]
It seems to be scaling weird. Ill take a look and see what I can figure out. Thanks for bringing this to my attention.

**Comment by Zodsmar** [comment]
Gonna test that this working when I get a chance and hopefully the GUI issues are fixed for now!
