### ISSUE TITLE
"Set Seeds" option disables the ability to use more than 1 core

### ISSUE THREAD

**Issue by RavingPlatypi** [Zodsmar/SeedSearcherStandaloneTool#130]
Hi! Not sure if this issue has been brought up but I find that whenever I search through set seeds I cannot change how many cores the program uses. I also cannot change the spawn point, but I saw in other closed issues that a full rewrite for 1.18 will fix that issue, so I am not too concerned.

For 1.18 I will be selecting a seed and my workflow is going to be as follows:

1. Generate 10000 seeds with all biome sets within 3k of spawn (0, 0).
2. Of those seeds, find which ones contain 2 woodland mansions, 20 witch huts, and 30 ocean monuments. Biomes/biome sets will not be specified.
3. Of those seeds, find which ones have 0 0 NOT be an ocean, icy biome, or jungle.

I'm not sure if this will work if searching through set seeds is this slow. Also, I know you haven't updated to 1.18 yet; I am just testing out this workflow on 1.17 so I am prepared to do it when 1.18 comes around.

Here is what I have selected for the "Data" page when I am on step 2 of my workflow:

```Seeds to find: 10000
Search radius: 7000
Incrementer: 50 (btw "Incrementer" is misspelled. The proper spelling is "Incrementor")
Biome Precision: 16

Then only "Set Seeds" is selected with the correct .txt file.```

**Comment by Zodsmar** [comment]
Yeah so what you want to do will work in 1.18. Set Seed searching should also be quite a bit faster in 1.18. Ill leave this open till I finish the rewrite as I will pretty much test all of these steps to make sure the flow is possible. Thanks!

**Comment by RavingPlatypi** [comment]
Ok cool! Thank you so much.

Just to be clear: is the inability to use more than 1 core for set seeds an intended feature or is it a bug?

**Comment by Zodsmar** [comment]
Kinda both. So because of how coupled and honestly how bad I wrote the code it was something I couldn't implement without a full rewrite. So I made the choice to lock it out. But since Im re writing it now, a lot of those issues are being resolved. I am making the flow of the app modular so I can do stuff like that.

**Comment by RavingPlatypi** [comment]
Gotcha! Sounds good dude. Thanks a lot. Very excited for the 1.18 rewrite :)

**Comment by RavingPlatypi** [comment]
I would also like to add that searching for biomes near spawn was SUPER FAST but searching for structures was incredibly slow. This was both with set seeds. Just thought I'd let you know in case it helps!
