### ISSUE TITLE
where is the download link for windows?

### ISSUE THREAD

**Issue by axelnieves2012** [Zodsmar/SeedSearcherStandaloneTool#138]
where is the download link for windows?

**Comment by Zodsmar** [comment]
On Github on the Right side of a repo is Releases tab. Click that and it shows all the releases. Under Assets is where the downloads are. For windows download the EXE. To make it easy here is the  [latest version](https://github.com/Zodsmar/SeedSearcherStandaloneTool/releases/tag/v0.6.3)
