### ISSUE TITLE
Linux version?

### ISSUE THREAD

**Issue by michaelpaulsen** [Zodsmar/SeedSearcherStandaloneTool#19]
I don't know if it is possible. I'm running ubuntu and the file system is different so when I start a search it fails to find the Minecraft install.

**Comment by Zodsmar** [comment]
I need to update it so you can pick where the minecraft install is itself. Instead of it being hardcoded to look for it!

**Comment by Zodsmar** [comment]
@michaelpaulsen v0.4.0 I just released has an option for changing the directory please let me know if it works now on linux

**Comment by michaelpaulsen** [comment]
seems to work... had to use \ instead of the normal (for Linux) / tho you might want to make it so that it prints something like "%dir% is not valid ( try using \'s) using default directory"(%dir% is the thing that they put in the input box)  to the textbox on the side, or in red below the input its self. or mabe just replace the /'s with \'s before it looks for the directory.

**Comment by Zodsmar** [comment]
Ill look into adding this. Thanks for bringing it to my attention

**Comment by Zodsmar** [comment]
This is old as you don't include the minecraft install directory anymore this is outdated
