### ISSUE TITLE
Console Output says "Please select Biomes first!"

### ISSUE THREAD

**Issue by Araxidis** [Zodsmar/SeedSearcherStandaloneTool#2]
After selecting several biomes, the console output still says Please select Biomes first! and pressing the Start button seemingly does nothing. Pressing the Clear button clears the console output but the Start button still does nothing.

**Comment by Zodsmar** [comment]
Do you have java 8 installed?

**Comment by Araxidis** [comment]
I actually have 8, 9 and 10 installed. Don't worry about it unless there's an easy fix. Thanks for the quick reply, though!
