### ISSUE TITLE
Multi Dungeon finder

### ISSUE THREAD

**Issue by ThePlayingGoblin** [Zodsmar/SeedSearcherStandaloneTool#23]
Attempts to search for multiple grouped together dungeons in a small area within the desired radius, including the option for Strictly a Certain Spawner Type. Useful if a player would like to have two or more skeleton spawners in a condensed area for the player to make a farm with.

**Comment by Zodsmar** [comment]
This feature is not possible. Minecraft dungeon generation happens at a different level than all other structures programmatically. It happens after the world itself is created. Seeds don't affect where dungeons spawn 100%. There are worlds where dungeons won't be in the same location in the same seed. Hard to explain but dungeon searching is nearly impossible at this point.
