### ISSUE TITLE
A bug or suggestion

### ISSUE THREAD

**Issue by Miha02** [Zodsmar/SeedSearcherStandaloneTool#3]
Im not sure if its a bug or its intended, but I think it would be better if "CLEAR" would clear "Total Rejected Seed Count".

**Comment by Miha02** [comment]
Im dumb

**Comment by Miha02** [comment]
Or im not

**Comment by anazopyreo** [comment]
A suggestion for future releases would be the ability to have separate distances for each biome. For example, I want an ocean pretty much right by spawn, maybe within 200 blocks, but I would like a desert that can be a bit farther out, maybe 1000 blocks.
I love his tool so far though. Thank you.

**Comment by Zodsmar** [comment]
Yeah I want to modify it still a lot. But have yet to figure out structures.
