### ISSUE TITLE
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

### ISSUE THREAD

**Issue by TCT9** [Zodsmar/SeedSearcherStandaloneTool#30]
How to resolve this error?

C:\Users\Ítalo\Desktop\Minecraft\SeedSearcherStandaloneTool-master\SeedSearcherStandaloneTool-master>gradlew.bat

Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain

Version gradle:
------------------------------------------------------------
Gradle 6.4.1
------------------------------------------------------------

Build time:   2020-05-15 19:43:40 UTC
Revision:     1a04183c502614b5c80e33d603074e0b4a2777c5

Kotlin:       1.3.71
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          14.0.1 (Oracle Corporation 14.0.1+7)
OS:           Windows 10 10.0 amd64

**Comment by Zodsmar** [comment]
is the gradlew.bat in the folder? Java can't find the gradlew not totally sure why Im using java 11 for development and your using 14. Could be related to that

**Comment by nightstick24** [comment]
Hey there, I'm also getting the same. Any ideas?

Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain

------------------------------------------------------------
Gradle 6.5.1
------------------------------------------------------------

Build time:   2020-06-30 06:32:47 UTC
Revision:     66bc713f7169626a7f0134bf452abde51550ea0a

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          14.0.1 (Oracle Corporation 14.0.1+7)
OS:           Windows 10 10.0 amd64

**Comment by ehoffman2** [comment]
Same here

Ubuntu 20.04
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)

**Comment by Zodsmar** [comment]
I will look into this reference thanks!

**Comment by OgalFinklestein** [comment]
Bump.
Maybe Im missing something, but it seems documentation is sorely lacking with this tool.  I try to avoid the memory-hogging Java as possible as often (exception being Minecraft), so when I pulled this repo I was hoping things would be a little more intuitive.
I see that `gradlew` is a shell script, but when I run it I get the same error listed as the title of this thread.  So how does one start up this tool?  There's no JAR, so I dont think I need to run Java first ...?  Am I supposed to install something?

Latest Debian.  OpenJDK 64-bit v11.0.8.

**Comment by OgalFinklestein** [comment]
FYI, I found a gradle package and installed it via `apt install gradle`.  Error still occurs.
Missing environment variables a possibility?

**Comment by Zodsmar** [comment]
> Bump.
> Maybe Im missing something, but it seems documentation is sorely lacking with this tool. I try to avoid the memory-hogging Java as possible as often (exception being Minecraft), so when I pulled this repo I was hoping things would be a little more intuitive.
> I see that `gradlew` is a shell script, but when I run it I get the same error listed as the title of this thread. So how does one start up this tool? There's no JAR, so I dont think I need to run Java first ...? Am I supposed to install something?
> 
> Latest Debian. OpenJDK 64-bit v11.0.8.

If you are just trying to run the tool to use. Go to releases and select the Assets dropdown to download a Jar or Exe. If you want to build it and mess with the code on Linux there is some documentation on the wiki on how to build for Linux provided by some other users
