### ISSUE TITLE
Search from a predefined list of seeds

### ISSUE THREAD

**Issue by Zodsmar** [Zodsmar/SeedSearcherStandaloneTool#38]
Be able to import maybe a TXT file with seeds already in it and search those for new criteria

**Comment by spetznack** [comment]
Yes! As an example it would be awesome to first search for a spawn biome - which can give you a big list real quick, then be able to use the results from that to search for more specific things afterwards.

**Comment by Tyler-Middendorf** [comment]
this is also nice for if you use an external tool to find quad witch hut seeds for example and apply other constraints like having at least 10 huts ant at least 1 monument ans such.

**Comment by Zerbu** [comment]
I really hope this becomes a thing! It would be really useful for performing an "advanced" search. For a real world example, I'm looking for seeds that meet a specific criteria: all warm biomes within a 1024 radius AND a desert village close to a savanna near spawn. (I know the program can't search for specific village types, but this would narrow my search down significantly)

**Comment by Zodsmar** [comment]
Added in @dylantknguyen 's PR
