### ISSUE TITLE
Bug: Some biomes are missing in the selector

### ISSUE THREAD

**Issue by GammaMicroscopii** [Zodsmar/SeedSearcherStandaloneTool#4]
I watched the OMGcraft video showcasing this tool 10 minutes ago, and I just downloaded it right now. I have counted the selectable biomes in the video, and I just counted them again with this tool in my hands: there are 71. But I know in minecraft 1.13 there are 73 biomes in total. So there are 2 biomes that are missing here. Those are Taiga Hills and Cold Taiga Hills.

**Comment by manuelgrabowski** [comment]
Cold Taiga Hills are listed in the code, though: https://github.com/Zodsmar/SeedSearcherStandaloneTool/blob/adb10b8b12e2317f8d5d3fdb5ba6428c2b4c7986/src/gui/GUI.java#L527

But no mention of "Taiga Hills" in the file, indeed.
