### ISSUE TITLE
search from x0/y0

### ISSUE THREAD

**Issue by LoneWolfProductions** [Zodsmar/SeedSearcherStandaloneTool#40]
Is it possible to add an option to search from x0/y0 instead of spawn?

(extra: an option to turn off (exclude) all biomes with one click would also be nice)

**Comment by Zodsmar** [comment]
Searching from a 0,0 will be added in the next version.

As for the option to turn off biomes, you can already just search for structures so I am not entirely sure what you mean. To not search for biomes just leave don't select any biomes.

**Comment by LoneWolfProductions** [comment]
Sorry for the late response.

By turning off i mean 'exclude all' so i can select the ones i want to be included only.

I assume that 
1) a blank field means "can be include but does not have to be"
2) include means must de in the search area
3) exclude means can not be in the search area

Or am I wrong?

For example i'm looking for a 256x256 warm ocean only. so i want to exclude all others to be not included. As off right now i need to exclude all others individualy. (kinda tedious you know)

Thanks for your time.

**Comment by Zodsmar** [comment]
It won't make it into this next release since the new version is coming out in the next little bit here. But ill see what I can do for the next version :)

**Comment by LoneWolfProductions** [comment]
Thank You
