### ISSUE TITLE
GUI unreadable

### ISSUE THREAD

**Issue by cburgard** [Zodsmar/SeedSearcherStandaloneTool#42]
I've just compiled SASSA on my machine (I'm running archlinux).
However, the GUI looks broken/unreadable (screenshot attached).
![Screenshot from 2020-06-23 19-18-48](https://user-images.githubusercontent.com/1086852/85434531-7916bd80-b586-11ea-9f4e-7233c215f3ee.png)
This looks not like it's intentional - there are no buttons, text fields, or anything. I suppose this might be related to my java version, or the GUI libs my OS is using.
What can I do to solve this?

**Comment by A4D4R** [comment]
See #28 (see latest comment for arch system, TDLR; `pacman -S java-openjfx` and `java -jar sassa-v0.5.0.jar`
No need to compile.

**Comment by cburgard** [comment]
Hey everyone!
Thanks so much for the quick replies. This is really impressive for such a small project - huge kudos!
I was able to resolve the GUI issue with your suggestions, but I'd like to add that I was only able to make it work with openjdk8 (switching via `archlinux-java set java-8-openjdk`). 

I also have some questions regarding the usage of the tool, but I'm not sure whether I should write them as issues here or if you have a chat somewhere. Any suggestion?

**Comment by Zodsmar** [comment]
you can make it an issue, or add me on discord or even follow me on twitter and DM me. Whatever works for you! Gonna close this for now since its been resolved and pertains to #28
