### ISSUE TITLE
Clearify search size

### ISSUE THREAD

**Issue by spetznack** [Zodsmar/SeedSearcherStandaloneTool#45]
Hi, 

The features says: "Search in specific radius from spawn"

Is the search size defined as radius, the total size of a rectangular area or a rectangular area defined by x distance from center? 
Around the 0 0 0 or the seed generated spawn point? 

I am specifically trying to find a nice seed for my server's survival world which will have a square world border size of 6000x60000 with x=0 z=0 as the center of the square. Ideally we would want all the different structures and special biomes that gives special mobs\resources, but I realize that is asking for a lot x)

**Comment by Zodsmar** [comment]
The search radius is around the spawn point and the radius is a square. So if you fo 512. It goes from -512,512 to positive 512,512 so technically 1024 across total.

The next version will be from 0,0 only.
