### ISSUE TITLE
Search in specific radius from spawn

### ISSUE THREAD

**Issue by stonar96** [Zodsmar/SeedSearcherStandaloneTool#46]
As already indicated in #45 "The next version will be from 0,0 only.". I think this is the case now, isn't it? However the README.md still says "from spawn".

For me it was a very important (if not the most important) feature to be able to search from spawn. It's a pity that this was removed. Is there any chance to readd this in a future update?

**Comment by Zodsmar** [comment]
I need to update the todo I must have missed that. I do plan on adding it back but it will significantly lower the speed. But yes its coming back.

**Comment by Zodsmar** [comment]
Added back. Will be in the next release (slightly different than before) you have more control over the spawn point now

**Comment by Delvin4519** [comment]
Just found this right after it got closed and saw it in the projects page. I need the option to still search from 0,0 though. Are both options going to be available together? 

I don't care about the spawn point, I only look at the world origin as that's where biomes are magnified/zoomed in/zoomed out. sometimes the spawn is inaccurate, but spawn is almost always within 512 in 0,0. and searching form 0,0 makes setting the worldborder easier, etc.

**Comment by Zodsmar** [comment]
By default, it will be 0,0. Searching from the spawn point isn't like it used to be. It's not just a setting to search around spawn point as that would kill the speed the tool has. So instead you can choose to search for a seed with a spawnpoint at a specific X and Z Coord with a Margin of Error Meaning I want it at 10, 30 but margin of error of 10 so if the spawn point is 11, 35 its still valid. A happy medium to keep the speed as well as open up the spawn point searching. 

But Yes 0,0 is default and always will be as it is the fastest method of searching.
