### ISSUE TITLE
Not searching randomly when structures are selected

### ISSUE THREAD

**Issue by ehoffman2** [Zodsmar/SeedSearcherStandaloneTool#51]
When including some structures in the search, the algorithm is no longer random, and always start at seed 0.

This can be seen if searching only for villages for example.

I think this come up to line 91 of sassa.searcher.Searcher.java

`if(si.size() != 0 && sg.getRandomSeed().isSelected()) {`
should be
`if(si.size() != 0 && !sg.getRandomSeed().isSelected()) {`

Eric

**Comment by Zodsmar** [comment]
The random is correct. It starts at 0 for speed sack. making it truly random slows it down.

**Comment by ehoffman2** [comment]
Should it then start the walk at a random location?

**Comment by Zodsmar** [comment]
the problem with that is threading. If you want to run multiple threads you need them to all start at different locations. But if you just randomly pick a few of the threads might start just millions of seeds off (meaning you might start getting duplicate seeds outputted and one of the threads might start looping whats already been looped wasting time.

**Comment by ehoffman2** [comment]
A way to do it would be would be to use a mask, for example masking the higher bits off, and using them for the thread number.  

Or, another way would be to divide the random start-of-walk number by the number of thread.  Each thread could start with an offset, ex: (search space / num thread) * thread ID.

The only thing is to handle the last thread possibly wrapping up, but if you remove the check that end the search if this max seed value is reached, then this would possibly work.  With 2^48 seed values, even the most powerful CPU will not search the entire space anyway.

Just a suggestion...

**Comment by Zodsmar** [comment]
Currently, I am breaking up the search space based on the number of threads but it always divides evenly starting from 0 to max. Ill look into this to make it more random

**Comment by Zodsmar** [comment]
Fixed. Will be in the next version
