### ISSUE TITLE
Creating instance of structures inside search.

### ISSUE THREAD

**Issue by racinmat** [Zodsmar/SeedSearcherStandaloneTool#55]
Is there a reason why new structure is created every time during the search in places like these?
- https://github.com/Zodsmar/SeedSearcherStandaloneTool/blob/master/src/main/java/sassa/searcher/Searcher.java#L39
- https://github.com/Zodsmar/SeedSearcherStandaloneTool/blob/master/src/main/java/sassa/searcher/Searcher.java#L82
- https://github.com/Zodsmar/SeedSearcherStandaloneTool/blob/master/src/main/java/sassa/searcher/StructureSearcher.java#L26
Is it because of multithreading that each thread needs it's own instance?
My understanding was that after starting the search seed, these structures are only read, not mutated, so it should not be needed, right?

**Comment by Zodsmar** [comment]
I don't quite follow, but every thread is checking a different seed so every thread needs to create a structureProvider since they are all operating on different seeds. If this is not what you mean, can you provide more details?
