### ISSUE TITLE
Use caching of BiomeSource objects

### ISSUE THREAD

**Issue by racinmat** [Zodsmar/SeedSearcherStandaloneTool#58]
In lots of places BiomeSource is created per each structure, but since this is quite heavy object and performs layer caching of biomes, it should be reused per same seed as much as possible: see https://discordapp.com/channels/505310901461581824/532998733135085578/749750365716480060

**Comment by Zodsmar** [comment]
That link doesnt seem to work. Could you provide more context? I understand what your getting at but not quite sure where you are seeing the problem
