### ISSUE TITLE
CREATING STRUCTURE SAMPLES

### ISSUE THREAD

**Issue by AydikoGamer2424** [Zodsmar/SeedSearcherStandaloneTool#61]
The biomes around the structure are changing, but the location and shape never change. Please fix it

**Comment by Zodsmar** [comment]
What do you mean?

**Comment by AydikoGamer2424** [comment]
So if I search for a woodland mansion nearby, the shape of the woodland mansion does not change at all.
And when I look for a mansion 150 locations it always shows the same seeds

**Comment by AydikoGamer2424** [comment]
And version 1.17 is coming

**Comment by Zodsmar** [comment]
> So if I search for a woodland mansion nearby, the shape of the woodland mansion does not change at all.
> And when I look for a mansion 150 locations it always shows the same seeds

Yes so because it uses structure seeds instead of regular seeds it searches for that specific structure. I am going to be implementing an option to make it more varied.

**Comment by AydikoGamer2424** [comment]
When will the next version come?

**Comment by Zodsmar** [comment]
When I get time to work on it

**Comment by AydikoGamer2424** [comment]
which one did you vote for mob vote

**Comment by Zodsmar** [comment]
> which one did you vote for mob vote

How is this relevant to Seed Searcher? (but if you must know Glow Squid Gang)

**Comment by AydikoGamer2424** [comment]
sorry

**Comment by AydikoGamer2424** [comment]
For example, your 0.5.0 vehicle is very different in the last version. and it's been searching for 44 minutes now and still can't find anything and my computer is getting very hot :)

**Comment by AydikoGamer2424** [comment]
Actually the tool is very nice

**Comment by Zodsmar** [comment]
Fixed this stuff. Will be in next release
