### ISSUE TITLE
Installation on Windows 10

### ISSUE THREAD

**Issue by aknight2015** [Zodsmar/SeedSearcherStandaloneTool#65]
How exactly do I get this working? A simple guide would help tremendously.

**Comment by Zodsmar** [comment]
There is an EXE and a JAR file run either and the application opens. 
https://github.com/Zodsmar/SeedSearcherStandaloneTool/releases then go to the bottom where it says ASSETS and click to drop it down and download the jar or exe

**Comment by aknight2015** [comment]
Thank you so much.
