### ISSUE TITLE
can't run any of the seed searcher tools (.jar and .exe runs only in background)

### ISSUE THREAD

**Issue by Delvin4519** [Zodsmar/SeedSearcherStandaloneTool#66]
the downloaded .exe and .jar do not run at all on my end

i tried the gradle bat/build options 
![image](https://user-images.githubusercontent.com/23464599/100368753-f7faa100-2fd1-11eb-838a-f8663e0bfc52.png)

**Comment by Delvin4519** [comment]
![image](https://user-images.githubusercontent.com/23464599/100368960-3ee89680-2fd2-11eb-9dd6-7b870c139539.png)

**Comment by Zodsmar** [comment]
The Gradle build won't work because the API's have updated and no longer support version 1_7. This was corrected in I believe the develop branch so try building that branch instead. As for the EXE and jars not working, I am not sure why they wouldn't be running without more info

**Comment by Delvin4519** [comment]
I try launching both the exe and jar, i cant find any output log or anything why they don't open

**Comment by Delvin4519** [comment]
I also tried doing javaw.exe -jar, it doesn't output anything though for why the seedsearcher it doesn't start up

**Comment by Delvin4519** [comment]
it only opens as a background process

**Comment by xXTeraXx** [comment]
Reinstall java

**Comment by Delvin4519** [comment]
I reinstalled jre and jdk already. I am on win10 20H2

running java -jar returns this 
![image](https://user-images.githubusercontent.com/23464599/101284317-6814de00-37ad-11eb-9ec5-ccb62af2b70e.png)

**Comment by Zodsmar** [comment]
New version is coming soon. Hopefully this won't be an issue but the issue with your building gradle bat and v1_7 has been fixed.

**Comment by Delvin4519** [comment]
![image](https://user-images.githubusercontent.com/23464599/103295197-75df0d00-49c1-11eb-8c7c-9350f5f988b9.png)

still only loads in the background, no windowed program

**Comment by Delvin4519** [comment]
![image](https://user-images.githubusercontent.com/23464599/103295240-8a230a00-49c1-11eb-8015-fc9f6cd1691f.png)
![image](https://user-images.githubusercontent.com/23464599/103295281-a0c96100-49c1-11eb-96da-50dbb2beffcf.png)

still loads only in the background, no windowed program

**Comment by Zodsmar** [comment]
What is your Environment Variable path. Just because you have both versions of Java installed my bet is that it is defaulting to 15.0.1. Make sure your JAVA_HOME env is pointing to Java 8.
You chn check this by running java --version

**Comment by Delvin4519** [comment]
I have only these variable set up
![image](https://user-images.githubusercontent.com/23464599/103315409-88723a00-49f3-11eb-9459-1a40dc9ac28d.png)
![image](https://user-images.githubusercontent.com/23464599/103315434-94f69280-49f3-11eb-85bb-95b3297ac927.png)

**Comment by Zodsmar** [comment]
Yeah see how your java version in the CMD is 15.0.1 you need it to be 1.8.0_271. Google how to set your system variable to be that version of java.

**Comment by Delvin4519** [comment]
I uninstalled jdk 15 and installed jdk 8, looks like it works now.

Might want to make note that if a user has jdk 15, make sure nothing points to that
