### ISSUE TITLE
20w14infinite

### ISSUE THREAD

**Issue by etherealxx** [Zodsmar/SeedSearcherStandaloneTool#68]
Can this tool used in infinite snapshot? If not, can you backport it? Coz there is a new category in Speedrun.com that involves infinite any%. Thank yau.

**Comment by xXTeraXx** [comment]
I do not know if this is true....

But none of the main dependencies that sassa uses to work have ever had the april fools release. Also....

You might be able to use a older version of sassa that relied on minecraft to work. But you would not be able to search for new "realms"

**Comment by Zodsmar** [comment]
> I do not know if this is true....
> 
> But none of the main dependencies that sassa uses to work have ever had the april fools release. Also....
> 
> You might be able to use a older version of sassa that relied on minecraft to work. But you would not be able to search for new "realms"

This is all very correct. The tool doesn't support new realms and I doubt I will ever add this. If I do it wont be for a very very long time
