### ISSUE TITLE
Ocean's Always True

### ISSUE THREAD

**Issue by Zodsmar** [Zodsmar/SeedSearcherStandaloneTool#7]
For some reason no matter what. The ocean biome is always detected as existing. No matter what..... hm.....

**Comment by Roisersy** [comment]
Anything new here?

**Comment by YourCoalAlt** [comment]
Are you saying the program "detects" an ocean but there is none in the world? Or the fact the "Ocean" option wasn't clickable before?

If you can, I have began a separate branch to continue support. You can try to see if the version I made fixes this issue: https://github.com/YourCoalAlt/SeedSearcherStandaloneTool/releases

**Comment by YourCoalAlt** [comment]
After testing it appears that it always requires Ocean for some reason, can't figure out how to change that.

**Comment by Zodsmar** [comment]
Most likely this will require a larger change, as YourCoal said, Amidst is most likely the cause so to really fine-tune the project we should probably drop amidst but I don't see that happening anytime soon. Writing the gen code that amidst is doing is a very large project.

**Comment by ProPaint** [comment]
I understood where the issue come from, the biomeCodes list returned by getBiomeCodes() is filled up with zero, an easy fix is to replace
`int biomeCodesCount = biomeCodes.length;	`

by
```
int biomesCodesCountSqrt = (int) Math.sqrt(this.mSearchQuadrantHeight*this.mSearchQuadrantWidth /4);
int biomeCodesCount = biomesCodesCountSqrt*biomesCodesCountSqrt;
```
