### ISSUE TITLE
Generating 1 too many seeds

### ISSUE THREAD

**Issue by Mlodko** [Zodsmar/SeedSearcherStandaloneTool#77]
In the version 0.6.1 the program outputs 11 seeds even though I selected 10 in the "seeds to find", I think the problem is that you forgot to subtract 1 from the variable handling the number of seeds it should find. (since computers count from 0) I couldn't find it in the source code but it should be a really easy fix

**Comment by Zodsmar** [comment]
Yeah sometimes it happens. I thought i fixed it previously I guess I did something that brought it back

**Comment by Zodsmar** [comment]
I just tested it and I can't seem to get it to go over what I set as the limit. If in the next version it is still there for you please reopen the ticket.
