### ISSUE TITLE
1.14 support

### ISSUE THREAD

**Issue by Roisersy** [Zodsmar/SeedSearcherStandaloneTool#8]
Is this supports 1.14 generation?

**Comment by YourCoalAlt** [comment]
I have created a branch of this respiratory that works with 1.14, you can try it out here: https://github.com/YourCoalAlt/SeedSearcherStandaloneTool/releases

**Comment by Zodsmar** [comment]
Awesome thanks for updating it to 1.14. I haven't had time but planned on it. Do you know how to add structure selection? This was the hurdle I kept trying to get over but never could and it was killed my drive for this project. If you could help me get structures searching working I have so many plans to keep going with.
