### ISSUE TITLE
Big oof

### ISSUE THREAD

**Issue by hube12** [Zodsmar/SeedSearcherStandaloneTool#90]
Uh, you should never had the master-Snapshot lines in your build.gradle, use SEED-master-snapshot since that repo is actually maintained https://kaptainwutax.seedfinding.com/docs/ and even so I recommend specifying a specific hash.
During the last month we changed a lot of the backend for the best and corrected a lot of bugs, this means that a ton of stuff got deprecated.

**Comment by Zodsmar** [comment]
Yeah in hindsight it was really stupid. Gonna be doing some major refactors to code, dependencies etc.
