### ISSUE TITLE
Snapshots? Ability to use installed MC jars to find seeds

### ISSUE THREAD

**Issue by HughSparks** [Zodsmar/SeedSearcherStandaloneTool#97]
I am looking for a way to pick out some seeds to use for a friend group smp. They all want certain features within a 1000 chunk radius so that we aren't ever to far away from each other. This tool is great for 1.16.5 but we would like to play on 21w14a which has new generation, I don't know if this would require a complete overhaul or semi-minor tweaks but would be a great feature. I have found a mapping tool that uses a similar method but I can't get it to play nice.

[Amidst](https://github.com/crbednarz/AMIDST) (mapping tool)

**Comment by Zodsmar** [comment]
This tool isn't actually reading any of the JAR's Im using dependencies which if I am not mistaken are also not reading the Jars. The generation code has been re-engineered for faster searching times. So running off of a jar won't be possible sorry
