### ISSUE TITLE
bintray sunset

### ISSUE THREAD

**Issue by cburgard** [Zodsmar/SeedSearcherStandaloneTool#99]
I'm really not a java guy, so forgive me if this is silly, but:
When trying to build, it complains about some dependencies from `jcenter.bintray.com` not being reachable, and a quick google search tells me that service is no longer available since a few days.
The dependency handling should really be updated!

**Comment by Zodsmar** [comment]
Ill look into it.

**Comment by Zodsmar** [comment]
Not even sure where the dependency is. Looking through the gradle it isn't even included. If you have a file location or something please post it.
